language: php

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.25.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - cd $TRAVIS_BUILD_DIR/.docker
  - make setup
  - echo "TRAVIS_JOB_ID=$TRAVIS_JOB_ID" >> .env
  - echo "TRAVIS=true" >> .env
  - echo "COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN" >> .env
  - echo "CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER" >> .env
  - echo "CI_BRANCH=$TRAVIS_BRANCH" >> .env
  - cat .env
  - cd $TRAVIS_BUILD_DIR/.docker/tests
  - make coverage

after_success:
  - make coveralls
