PUT http://{{host}}/order?XDEBUG_SESSION_START=1
Content-Type: application/json

{
    "products": [1]
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
